// iife country flags module
const CountryFlags = (function() {
    // country data: two-letter code -> { code: three-letter, name: full name, flag: unicode }
    const flags = {
        "AF": { code: "AFG", name: "Afghanistan", flag: "🇦🇫" },
        "AL": { code: "ALB", name: "Albania", flag: "🇦🇱" },
        "DZ": { code: "DZA", name: "Algeria", flag: "🇩🇿" },
        "AD": { code: "AND", name: "Andorra", flag: "🇦🇩" },
        "AO": { code: "AGO", name: "Angola", flag: "🇦🇴" },
        "AG": { code: "ATG", name: "Antigua and Barbuda", flag: "🇦🇬" },
        "AR": { code: "ARG", name: "Argentina", flag: "🇦🇷" },
        "AM": { code: "ARM", name: "Armenia", flag: "🇦🇲" },
        "AU": { code: "AUS", name: "Australia", flag: "🇦🇺" },
        "AT": { code: "AUT", name: "Austria", flag: "🇦🇹" },
        "AZ": { code: "AZE", name: "Azerbaijan", flag: "🇦🇿" },
        "BS": { code: "BHS", name: "Bahamas", flag: "🇧🇸" },
        "BH": { code: "BHR", name: "Bahrain", flag: "🇧🇭" },
        "BD": { code: "BGD", name: "Bangladesh", flag: "🇧🇩" },
        "BB": { code: "BRB", name: "Barbados", flag: "🇧🇧" },
        "BY": { code: "BLR", name: "Belarus", flag: "🇧🇾" },
        "BE": { code: "BEL", name: "Belgium", flag: "🇧🇪" },
        "BZ": { code: "BLZ", name: "Belize", flag: "🇧🇿" },
        "BJ": { code: "BEN", name: "Benin", flag: "🇧🇯" },
        "BT": { code: "BTN", name: "Bhutan", flag: "🇧🇹" },
        "BO": { code: "BOL", name: "Bolivia", flag: "🇧🇴" },
        "BA": { code: "BIH", name: "Bosnia and Herzegovina", flag: "🇧🇦" },
        "BW": { code: "BWA", name: "Botswana", flag: "🇧🇼" },
        "BR": { code: "BRA", name: "Brazil", flag: "🇧🇷" },
        "BN": { code: "BRN", name: "Brunei", flag: "🇧🇳" },
        "BG": { code: "BGR", name: "Bulgaria", flag: "🇧🇬" },
        "BF": { code: "BFA", name: "Burkina Faso", flag: "🇧🇫" },
        "BI": { code: "BDI", name: "Burundi", flag: "🇧🇮" },
        "KH": { code: "KHM", name: "Cambodia", flag: "🇰🇭" },
        "CM": { code: "CMR", name: "Cameroon", flag: "🇨🇲" },
        "CA": { code: "CAN", name: "Canada", flag: "🇨🇦" },
        "CV": { code: "CPV", name: "Cape Verde", flag: "🇨🇻" },
        "CF": { code: "CAF", name: "Central African Republic", flag: "🇨🇫" },
        "TD": { code: "TCD", name: "Chad", flag: "🇹🇩" },
        "CL": { code: "CHL", name: "Chile", flag: "🇨🇱" },
        "CN": { code: "CHN", name: "China", flag: "🇨🇳" },
        "CO": { code: "COL", name: "Colombia", flag: "🇨🇴" },
        "KM": { code: "COM", name: "Comoros", flag: "🇰🇲" },
        "CG": { code: "COG", name: "Congo (Brazzaville)", flag: "🇨🇬" },
        "CD": { code: "COD", name: "Congo (Kinshasa)", flag: "🇨🇩" },
        "CR": { code: "CRI", name: "Costa Rica", flag: "🇨🇷" },
        "CI": { code: "CIV", name: "Côte d'Ivoire", flag: "🇨🇮" },
        "HR": { code: "HRV", name: "Croatia", flag: "🇭🇷" },
        "CU": { code: "CUB", name: "Cuba", flag: "🇨🇺" },
        "CY": { code: "CYP", name: "Cyprus", flag: "🇨🇾" },
        "CZ": { code: "CZE", name: "Czechia", flag: "🇨🇿" },
        "DK": { code: "DNK", name: "Denmark", flag: "🇩🇰" },
        "DJ": { code: "DJI", name: "Djibouti", flag: "🇩🇯" },
        "DM": { code: "DMA", name: "Dominica", flag: "🇩🇲" },
        "DO": { code: "DOM", name: "Dominican Republic", flag: "🇩🇴" },
        "EC": { code: "ECU", name: "Ecuador", flag: "🇪🇨" },
        "EG": { code: "EGY", name: "Egypt", flag: "🇪🇬" },
        "SV": { code: "SLV", name: "El Salvador", flag: "🇸🇻" },
        "GQ": { code: "GNQ", name: "Equatorial Guinea", flag: "🇬🇶" },
        "ER": { code: "ERI", name: "Eritrea", flag: "🇪🇷" },
        "EE": { code: "EST", name: "Estonia", flag: "🇪🇪" },
        "SZ": { code: "SWZ", name: "Eswatini", flag: "🇸🇿" },
        "ET": { code: "ETH", name: "Ethiopia", flag: "🇪🇹" },
        "FJ": { code: "FJI", name: "Fiji", flag: "🇫🇯" },
        "FI": { code: "FIN", name: "Finland", flag: "🇫🇮" },
        "FR": { code: "FRA", name: "France", flag: "🇫🇷" },
        "GA": { code: "GAB", name: "Gabon", flag: "🇬🇦" },
        "GM": { code: "GMB", name: "Gambia", flag: "🇬🇲" },
        "GE": { code: "GEO", name: "Georgia", flag: "🇬🇪" },
        "DE": { code: "DEU", name: "Germany", flag: "🇩🇪" },
        "GH": { code: "GHA", name: "Ghana", flag: "🇬🇭" },
        "GR": { code: "GRC", name: "Greece", flag: "🇬🇷" },
        "GD": { code: "GRD", name: "Grenada", flag: "🇬🇩" },
        "GT": { code: "GTM", name: "Guatemala", flag: "🇬🇹" },
        "GN": { code: "GIN", name: "Guinea", flag: "🇬🇳" },
        "GW": { code: "GNB", name: "Guinea-Bissau", flag: "🇬🇼" },
        "GY": { code: "GUY", name: "Guyana", flag: "🇬🇾" },
        "HT": { code: "HTI", name: "Haiti", flag: "🇭🇹" },
        "HN": { code: "HND", name: "Honduras", flag: "🇭🇳" },
        "HU": { code: "HUN", name: "Hungary", flag: "🇭🇺" },
        "IS": { code: "ISL", name: "Iceland", flag: "🇮🇸" },
        "IN": { code: "IND", name: "India", flag: "🇮🇳" },
        "ID": { code: "IDN", name: "Indonesia", flag: "🇮🇩" },
        "IR": { code: "IRN", name: "Iran", flag: "🇮🇷" },
        "IQ": { code: "IRQ", name: "Iraq", flag: "🇮🇶" },
        "IE": { code: "IRL", name: "Ireland", flag: "🇮🇪" },
        "IL": { code: "ISR", name: "Israel", flag: "🇮🇱" },
        "IT": { code: "ITA", name: "Italy", flag: "🇮🇹" },
        "JM": { code: "JAM", name: "Jamaica", flag: "🇯🇲" },
        "JP": { code: "JPN", name: "Japan", flag: "🇯🇵" },
        "JO": { code: "JOR", name: "Jordan", flag: "🇯🇴" },
        "KZ": { code: "KAZ", name: "Kazakhstan", flag: "🇰🇿" },
        "KE": { code: "KEN", name: "Kenya", flag: "🇰🇪" },
        "KI": { code: "KIR", name: "Kiribati", flag: "🇰🇮" },
        "KP": { code: "PRK", name: "North Korea", flag: "🇰🇵" },
        "KR": { code: "KOR", name: "South Korea", flag: "🇰🇷" },
        "KW": { code: "KWT", name: "Kuwait", flag: "🇰🇼" },
        "KG": { code: "KGZ", name: "Kyrgyzstan", flag: "🇰🇬" },
        "LA": { code: "LAO", name: "Laos", flag: "🇱🇦" },
        "LV": { code: "LVA", name: "Latvia", flag: "🇱🇻" },
        "LB": { code: "LBN", name: "Lebanon", flag: "🇱🇧" },
        "LS": { code: "LSO", name: "Lesotho", flag: "🇱🇸" },
        "LR": { code: "LBR", name: "Liberia", flag: "🇱🇷" },
        "LY": { code: "LBY", name: "Libya", flag: "🇱🇾" },
        "LI": { code: "LIE", name: "Liechtenstein", flag: "🇱🇮" },
        "LT": { code: "LTU", name: "Lithuania", flag: "🇱🇹" },
        "LU": { code: "LUX", name: "Luxembourg", flag: "🇱🇺" },
        "MG": { code: "MDG", name: "Madagascar", flag: "🇲🇬" },
        "MW": { code: "MWI", name: "Malawi", flag: "🇲🇼" },
        "MY": { code: "MYS", name: "Malaysia", flag: "🇲🇾" },
        "MV": { code: "MDV", name: "Maldives", flag: "🇲🇻" },
        "ML": { code: "MLI", name: "Mali", flag: "🇲🇱" },
        "MT": { code: "MLT", name: "Malta", flag: "🇲🇹" },
        "MH": { code: "MHL", name: "Marshall Islands", flag: "🇲🇭" },
        "MR": { code: "MRT", name: "Mauritania", flag: "🇲🇷" },
        "MU": { code: "MUS", name: "Mauritius", flag: "🇲🇺" },
        "MX": { code: "MEX", name: "Mexico", flag: "🇲🇽" },
        "FM": { code: "FSM", name: "Micronesia", flag: "🇫🇲" },
        "MD": { code: "MDA", name: "Moldova", flag: "🇲🇩" },
        "MC": { code: "MCO", name: "Monaco", flag: "🇲🇨" },
        "MN": { code: "MNG", name: "Mongolia", flag: "🇲🇳" },
        "ME": { code: "MNE", name: "Montenegro", flag: "🇲🇪" },
        "MA": { code: "MAR", name: "Morocco", flag: "🇲🇦" },
        "MZ": { code: "MOZ", name: "Mozambique", flag: "🇲🇿" },
        "MM": { code: "MMR", name: "Myanmar", flag: "🇲🇲" },
        "NA": { code: "NAM", name: "Namibia", flag: "🇳🇦" },
        "NR": { code: "NRU", name: "Nauru", flag: "🇳🇷" },
        "NP": { code: "NPL", name: "Nepal", flag: "🇳🇵" },
        "NL": { code: "NLD", name: "Netherlands", flag: "🇳🇱" },
        "NZ": { code: "NZL", name: "New Zealand", flag: "🇳🇿" },
        "NI": { code: "NIC", name: "Nicaragua", flag: "🇳🇮" },
        "NE": { code: "NER", name: "Niger", flag: "🇳🇪" },
        "NG": { code: "NGA", name: "Nigeria", flag: "🇳🇬" },
        "MK": { code: "MKD", name: "North Macedonia", flag: "🇲🇰" },
        "NO": { code: "NOR", name: "Norway", flag: "🇳🇴" },
        "OM": { code: "OMN", name: "Oman", flag: "🇴🇲" },
        "PK": { code: "PAK", name: "Pakistan", flag: "🇵🇰" },
        "PW": { code: "PLW", name: "Palau", flag: "🇵🇼" },
        "PS": { code: "PSE", name: "Palestine", flag: "🇵🇸" },
        "PA": { code: "PAN", name: "Panama", flag: "🇵🇦" },
        "PG": { code: "PNG", name: "Papua New Guinea", flag: "🇵🇬" },
        "PY": { code: "PRY", name: "Paraguay", flag: "🇵🇾" },
        "PE": { code: "PER", name: "Peru", flag: "🇵🇪" },
        "PH": { code: "PHL", name: "Philippines", flag: "🇵🇭" },
        "PL": { code: "POL", name: "Poland", flag: "🇵🇱" },
        "PT": { code: "PRT", name: "Portugal", flag: "🇵🇹" },
        "QA": { code: "QAT", name: "Qatar", flag: "🇶🇦" },
        "RO": { code: "ROU", name: "Romania", flag: "🇷🇴" },
        "RU": { code: "RUS", name: "Russia", flag: "🇷🇺" },
        "RW": { code: "RWA", name: "Rwanda", flag: "🇷🇼" },
        "KN": { code: "KNA", name: "Saint Kitts and Nevis", flag: "🇰🇳" },
        "LC": { code: "LCA", name: "Saint Lucia", flag: "🇱🇨" },
        "VC": { code: "VCT", name: "Saint Vincent and the Grenadines", flag: "🇻🇨" },
        "WS": { code: "WSM", name: "Samoa", flag: "🇼🇸" },
        "SM": { code: "SMR", name: "San Marino", flag: "🇸🇲" },
        "ST": { code: "STP", name: "Sao Tome and Principe", flag: "🇸🇹" },
        "SA": { code: "SAU", name: "Saudi Arabia", flag: "🇸🇦" },
        "SN": { code: "SEN", name: "Senegal", flag: "🇸🇳" },
        "RS": { code: "SRB", name: "Serbia", flag: "🇷🇸" },
        "SC": { code: "SYC", name: "Seychelles", flag: "🇸🇨" },
        "SL": { code: "SLE", name: "Sierra Leone", flag: "🇸🇱" },
        "SG": { code: "SGP", name: "Singapore", flag: "🇸🇬" },
        "SK": { code: "SVK", name: "Slovakia", flag: "🇸🇰" },
        "SI": { code: "SVN", name: "Slovenia", flag: "🇸🇮" },
        "SB": { code: "SLB", name: "Solomon Islands", flag: "🇸🇧" },
        "SO": { code: "SOM", name: "Somalia", flag: "🇸🇴" },
        "ZA": { code: "ZAF", name: "South Africa", flag: "🇿🇦" },
        "SS": { code: "SSD", name: "South Sudan", flag: "🇸🇸" },
        "ES": { code: "ESP", name: "Spain", flag: "🇪🇸" },
        "LK": { code: "LKA", name: "Sri Lanka", flag: "🇱🇰" },
        "SD": { code: "SDN", name: "Sudan", flag: "🇸🇩" },
        "SR": { code: "SUR", name: "Suriname", flag: "🇸🇷" },
        "SE": { code: "SWE", name: "Sweden", flag: "🇸🇪" },
        "CH": { code: "CHE", name: "Switzerland", flag: "🇨🇭" },
        "SY": { code: "SYR", name: "Syria", flag: "🇸🇾" },
        "TW": { code: "TWN", name: "Taiwan", flag: "🇹🇼" },
        "TJ": { code: "TJK", name: "Tajikistan", flag: "🇹🇯" },
        "TZ": { code: "TZA", name: "Tanzania", flag: "🇹🇿" },
        "TH": { code: "THA", name: "Thailand", flag: "🇹🇭" },
        "TL": { code: "TLS", name: "Timor-Leste", flag: "🇹🇱" },
        "TG": { code: "TGO", name: "Togo", flag: "🇹🇬" },
        "TO": { code: "TON", name: "Tonga", flag: "🇹🇴" },
        "TT": { code: "TTO", name: "Trinidad and Tobago", flag: "🇹🇹" },
        "TN": { code: "TUN", name: "Tunisia", flag: "🇹🇳" },
        "TR": { code: "TUR", name: "Turkey", flag: "🇹🇷" },
        "TM": { code: "TKM", name: "Turkmenistan", flag: "🇹🇲" },
        "TV": { code: "TUV", name: "Tuvalu", flag: "🇹🇻" },
        "UG": { code: "UGA", name: "Uganda", flag: "🇺🇬" },
        "UA": { code: "UKR", name: "Ukraine", flag: "🇺🇦" },
        "AE": { code: "ARE", name: "United Arab Emirates", flag: "🇦🇪" },
        "GB": { code: "GBR", name: "United Kingdom", flag: "🇬🇧" },
        "US": { code: "USA", name: "United States", flag: "🇺🇸" },
        "UY": { code: "URY", name: "Uruguay", flag: "🇺🇾" },
        "UZ": { code: "UZB", name: "Uzbekistan", flag: "🇺🇿" },
        "VU": { code: "VUT", name: "Vanuatu", flag: "🇻🇺" },
        "VA": { code: "VAT", name: "Vatican City", flag: "🇻🇦" },
        "VE": { code: "VEN", name: "Venezuela", flag: "🇻🇪" },
        "VN": { code: "VNM", name: "Vietnam", flag: "🇻🇳" },
        "YE": { code: "YEM", name: "Yemen", flag: "🇾🇪" },
        "ZM": { code: "ZMB", name: "Zambia", flag: "🇿🇲" },
        "ZW": { code: "ZWE", name: "Zimbabwe", flag: "🇿🇼" }
    };
    
    return {
        getCountryInfo: function(code) {
            const upperCode = (code || "").toUpperCase().slice(0, 2);
            return flags[upperCode] || null;
        }
    };
})();

// Usage example:
// const info = CountryFlags.getCountryInfo("US");
// console.log(info); // { code: "USA", name: "United States", flag: "🇺🇸" }